package:
    name: libprotobuf
    version: 2.6.1

source:
    fn: protobuf-2.6.1.tar.gz
    url: https://github.com/google/protobuf/releases/download/v2.6.1/protobuf-2.6.1.tar.gz

build:
    number: 0

about:
    home: https://developers.google.com/protocol-buffers/
    license: Apache
